/*
 * This file is generated by jOOQ.
 */
package com.ayushrawat.auth.jooq.tables.records;


import com.ayushrawat.auth.jooq.tables.RefreshTokens;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RefreshTokensRecord extends UpdatableRecordImpl<RefreshTokensRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.refresh_tokens.id</code>.
     */
    public RefreshTokensRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.refresh_tokens.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.refresh_tokens.refresh_token</code>.
     */
    public RefreshTokensRecord setRefreshToken(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.refresh_tokens.refresh_token</code>.
     */
    public String getRefreshToken() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.refresh_tokens.user_id</code>.
     */
    public RefreshTokensRecord setUserId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.refresh_tokens.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.refresh_tokens.expiry_date</code>.
     */
    public RefreshTokensRecord setExpiryDate(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.refresh_tokens.expiry_date</code>.
     */
    public LocalDateTime getExpiryDate() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RefreshTokensRecord
     */
    public RefreshTokensRecord() {
        super(RefreshTokens.REFRESH_TOKENS);
    }

    /**
     * Create a detached, initialised RefreshTokensRecord
     */
    public RefreshTokensRecord(Integer id, String refreshToken, Integer userId, LocalDateTime expiryDate) {
        super(RefreshTokens.REFRESH_TOKENS);

        setId(id);
        setRefreshToken(refreshToken);
        setUserId(userId);
        setExpiryDate(expiryDate);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised RefreshTokensRecord
     */
    public RefreshTokensRecord(com.ayushrawat.auth.jooq.tables.pojos.RefreshTokens value) {
        super(RefreshTokens.REFRESH_TOKENS);

        if (value != null) {
            setId(value.getId());
            setRefreshToken(value.getRefreshToken());
            setUserId(value.getUserId());
            setExpiryDate(value.getExpiryDate());
            resetChangedOnNotNull();
        }
    }
}
