/*
 * This file is generated by jOOQ.
 */
package com.ayushrawat.auth.jooq;


import com.ayushrawat.auth.jooq.tables.RefreshTokens;
import com.ayushrawat.auth.jooq.tables.Users;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.refresh_tokens</code>.
     */
    public static final RefreshTokens REFRESH_TOKENS = RefreshTokens.REFRESH_TOKENS;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
