/*
 * This file is generated by jOOQ.
 */
package com.ayushrawat.auth.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RefreshTokens implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String refreshToken;
    private Integer userId;
    private LocalDateTime expiryDate;

    public RefreshTokens() {}

    public RefreshTokens(RefreshTokens value) {
        this.id = value.id;
        this.refreshToken = value.refreshToken;
        this.userId = value.userId;
        this.expiryDate = value.expiryDate;
    }

    public RefreshTokens(
        Integer id,
        String refreshToken,
        Integer userId,
        LocalDateTime expiryDate
    ) {
        this.id = id;
        this.refreshToken = refreshToken;
        this.userId = userId;
        this.expiryDate = expiryDate;
    }

    /**
     * Getter for <code>public.refresh_tokens.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.refresh_tokens.id</code>.
     */
    public RefreshTokens setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.refresh_tokens.refresh_token</code>.
     */
    public String getRefreshToken() {
        return this.refreshToken;
    }

    /**
     * Setter for <code>public.refresh_tokens.refresh_token</code>.
     */
    public RefreshTokens setRefreshToken(String refreshToken) {
        this.refreshToken = refreshToken;
        return this;
    }

    /**
     * Getter for <code>public.refresh_tokens.user_id</code>.
     */
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>public.refresh_tokens.user_id</code>.
     */
    public RefreshTokens setUserId(Integer userId) {
        this.userId = userId;
        return this;
    }

    /**
     * Getter for <code>public.refresh_tokens.expiry_date</code>.
     */
    public LocalDateTime getExpiryDate() {
        return this.expiryDate;
    }

    /**
     * Setter for <code>public.refresh_tokens.expiry_date</code>.
     */
    public RefreshTokens setExpiryDate(LocalDateTime expiryDate) {
        this.expiryDate = expiryDate;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final RefreshTokens other = (RefreshTokens) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.refreshToken == null) {
            if (other.refreshToken != null)
                return false;
        }
        else if (!this.refreshToken.equals(other.refreshToken))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.expiryDate == null) {
            if (other.expiryDate != null)
                return false;
        }
        else if (!this.expiryDate.equals(other.expiryDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.refreshToken == null) ? 0 : this.refreshToken.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.expiryDate == null) ? 0 : this.expiryDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RefreshTokens (");

        sb.append(id);
        sb.append(", ").append(refreshToken);
        sb.append(", ").append(userId);
        sb.append(", ").append(expiryDate);

        sb.append(")");
        return sb.toString();
    }
}
