/*
 * This file is generated by jOOQ.
 */
package com.ayushrawat.auth.jooq.tables;


import com.ayushrawat.auth.jooq.Keys;
import com.ayushrawat.auth.jooq.Public;
import com.ayushrawat.auth.jooq.tables.records.RefreshTokensRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RefreshTokens extends TableImpl<RefreshTokensRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.refresh_tokens</code>
     */
    public static final RefreshTokens REFRESH_TOKENS = new RefreshTokens();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RefreshTokensRecord> getRecordType() {
        return RefreshTokensRecord.class;
    }

    /**
     * The column <code>public.refresh_tokens.id</code>.
     */
    public final TableField<RefreshTokensRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.refresh_tokens.refresh_token</code>.
     */
    public final TableField<RefreshTokensRecord, String> REFRESH_TOKEN = createField(DSL.name("refresh_token"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.refresh_tokens.user_id</code>.
     */
    public final TableField<RefreshTokensRecord, Integer> USER_ID = createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.refresh_tokens.expiry_date</code>.
     */
    public final TableField<RefreshTokensRecord, LocalDateTime> EXPIRY_DATE = createField(DSL.name("expiry_date"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    private RefreshTokens(Name alias, Table<RefreshTokensRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private RefreshTokens(Name alias, Table<RefreshTokensRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.refresh_tokens</code> table reference
     */
    public RefreshTokens(String alias) {
        this(DSL.name(alias), REFRESH_TOKENS);
    }

    /**
     * Create an aliased <code>public.refresh_tokens</code> table reference
     */
    public RefreshTokens(Name alias) {
        this(alias, REFRESH_TOKENS);
    }

    /**
     * Create a <code>public.refresh_tokens</code> table reference
     */
    public RefreshTokens() {
        this(DSL.name("refresh_tokens"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<RefreshTokensRecord, Integer> getIdentity() {
        return (Identity<RefreshTokensRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<RefreshTokensRecord> getPrimaryKey() {
        return Keys.REFRESH_TOKENS_PKEY;
    }

    @Override
    public List<UniqueKey<RefreshTokensRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.REFRESH_TOKENS_REFRESH_TOKEN_KEY);
    }

    @Override
    public RefreshTokens as(String alias) {
        return new RefreshTokens(DSL.name(alias), this);
    }

    @Override
    public RefreshTokens as(Name alias) {
        return new RefreshTokens(alias, this);
    }

    @Override
    public RefreshTokens as(Table<?> alias) {
        return new RefreshTokens(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public RefreshTokens rename(String name) {
        return new RefreshTokens(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RefreshTokens rename(Name name) {
        return new RefreshTokens(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public RefreshTokens rename(Table<?> name) {
        return new RefreshTokens(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RefreshTokens where(Condition condition) {
        return new RefreshTokens(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RefreshTokens where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RefreshTokens where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RefreshTokens where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RefreshTokens where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RefreshTokens where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RefreshTokens where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RefreshTokens where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RefreshTokens whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RefreshTokens whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
